### ISSUE TITLE
The models you given in the Instructions is not useable

### ISSUE THREAD

**Issue by zhenglm** [YerevaNN/R-NET-in-Keras#20]
python predict.py --batch_size 100 --dev_data data/dev_data_str.pkl models/31-t3.05458271443-v3.27696280528.model prediction.json
Preparing model...Traceback (most recent call last):
  File "predict.py", line 33, in <module>
    model = load_model(args.model, custom_objects())
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 233, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 307, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2450, in from_config
    process_layer(layer_data)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2447, in process_layer
    layer(input_tensors, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 571, in __call__
    self.build(input_shapes)
  File "/home/zhengliming/Keras_2.0.6/R-NET-in-Keras/layers/QuestionPooling.py", line 26, in build
    assert(isinstance(input_shape, list) and len(input_shape) == 5)
AssertionError

**Comment by MartinXPN** [comment]
This issue is caused because of the same problem addressed in Issue #13  https://github.com/YerevaNN/R-NET-in-Keras/issues/13

Please see the solution suggested there

**Comment by zhenglm** [comment]
OK， Thanks
