### ISSUE TITLE
P_str shape mismatch for tranining

### ISSUE THREAD

**Issue by roozbehataisera** [YerevaNN/R-NET-in-Keras#21]
Thanks for the implementation. During the training I get the following error. 

```
python train.py --hdim 45 --batch_size 50 --nb_epochs 50 --optimizer adadelta --lr 1 --dropout 0.2 --char_level_embeddings --train_data data/train_data_str.pkl --valid_data data/valid_data_str.pkl

Using TensorFlow backend.
Creating the model...Done!
Compiling Keras model...Done!
Loading datasets...Done!
Preparing generators...Done!
Training...Epoch 1/50
Traceback (most recent call last):
  File "train.py", line 70, in <module>
    ModelCheckpoint(path, verbose=1, save_best_only=True)
  File "/Users/roozbehdavari/anaconda3/envs/python2/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/Users/roozbehdavari/anaconda3/envs/python2/lib/python2.7/site-packages/keras/engine/training.py", line 1840, in fit_generator
    class_weight=class_weight)
  File "/Users/roozbehdavari/anaconda3/envs/python2/lib/python2.7/site-packages/keras/engine/training.py", line 1559, in train_on_batch
    check_batch_axis=True)
  File "/Users/roozbehdavari/anaconda3/envs/python2/lib/python2.7/site-packages/keras/engine/training.py", line 1234, in _standardize_user_data
    exception_prefix='input')
  File "/Users/roozbehdavari/anaconda3/envs/python2/lib/python2.7/site-packages/keras/engine/training.py", line 140, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking input: expected P_str to have shape (None, None, 25) but got array with shape (50, 300, 300)
```

I checked P_str dimension during "Creating the model..." step and the shape is (None, None, 25). I don't understand I what step the shape changes.

**Comment by roozbehataisera** [comment]
The training dataset was create without using --include_str but during training enabled --char_level_embeddings.
