### ISSUE TITLE
ValueError: need more than 0 values to unpack 

### ISSUE THREAD

**Issue by jayajackson** [YerevaNN/R-NET-in-Keras#24]
Hi,
     I got the above mentioned error,while  I run the training process

Thanking You

Traceback (most recent call last):
  File "train.py", line 39, in <module>
    char_level_embeddings=args.char_level_embeddings)
  File "/home/lab/Desktop/project/R-NET-in-Keras-master/model.py", line 106, in __init__
    WQ_u, WP_v, WP_u, v
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 262, in __call__
    return super(Recurrent, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 596, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/lab/Desktop/project/R-NET-in-Keras-master/WrappedGRU.py", line 49, in call
    return super(WrappedGRU, self).call(inputs, mask, training)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 341, in call
    input_length=input_shape[1])
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2457, in rnn
    outputs, _ = step_function(inputs[0], initial_states + constants)
  File "/home/lab/Desktop/project/R-NET-in-Keras-master/QuestionAttnGRU.py", line 37, in step
    uQ_mask, = states[9:10]
ValueError: need more than 0 values to unpack

**Comment by mahnerak** [comment]
@jayajackson Please make sure you are running Keras version 2.0.6

**Comment by jayajackson** [comment]
Dear sir,
            I changed keras version to 2.0.6.but... Still showing the same
error.


Thanking You

**Comment by jayajackson** [comment]
Dear sir,
            I have changed keras version to 2.0.6.but... Still showing the
same error.


Thanking You

**Comment by jayajackson** [comment]
Dear sir,


            I have changed the keras version.But showing the same error.


Thanking You
