### ISSUE TITLE
Imput number error

### ISSUE THREAD

**Issue by konrajak** [YerevaNN/R-NET-in-Keras#7]
I've been trying to train a model using your implementation but I am unable to run the training script due to following error. 
 

> Creating the model...Traceback (most recent call last):
  File "/home/ubuntu/R-NET-in-Keras/train.py", line 39, in <module>
    char_level_embeddings=args.char_level_embeddings)
  File "/home/ubuntu/R-NET-in-Keras/model.py", line 99, in __init__
    unroll=unroll) ([uP, uQ,WQ_u, WP_v, WP_u, v, W_g1])
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 294, in __call__
    output = super(Recurrent, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 558, in __call__
    self.assert_input_compatibility(inputs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 445, in assert_input_compatibility
    str(inputs))
ValueError: Layer question_attn_gru_1 expects 2 inputs, but it received 7 input tensors. Input received: [<tf.Tensor 'uP/cond/Merge:0' shape=(?, ?, 90) dtype=float32>, <tf.Tensor 'uQ/cond/Merge:0' shape=(?, ?, 90) dtype=float32>, <tf.Tensor 'mul_1:0' shape=(90, 45) dtype=float32>, <tf.Tensor 'mul_3:0' shape=(45, 45) dtype=float32>, <tf.Tensor 'mul_2:0' shape=(90, 45) dtype=float32>, <tf.Tensor 'mul:0' shape=(45, 1) dtype=float32>, <tf.Tensor 'mul_4:0' shape=(180, 180) dtype=float32>]

Process finished with exit code 1

I ran your code as is and followed your instructions.
Can you help me figure out what is causing this problem?

**Comment by mahnerak** [comment]
@konrajak We have a bug, that's whty it doesn't work in Keras 2.0.8.
I'll try to fix that ASAP, but you can try `pip install keras=2.0.6` before the problem is fixed.

**Comment by konrajak** [comment]
@mahnerak  I downgraded to 2.0.6 and the model builds fine now. However, I encountered another problem when training the model.

> Using TensorFlow backend.
Creating the model...Done!
Compiling Keras model...Done!
Loading datasets...Done!
Preparing generators...Done!
Training...Epoch 1/50
Traceback (most recent call last):
  File "/home/ubuntu/R-NET-in-Keras/train.py", line 72, in <module>
    ModelCheckpoint(path, verbose=1, save_best_only=True)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1840, in fit_generator
    class_weight=class_weight)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1559, in train_on_batch
    check_batch_axis=True)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1234, in _standardize_user_data
    exception_prefix='input')
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 140, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking input: expected Q_vecs to have shape (None, None, 300) but got array with shape (50, 30, 25)

I tried it with the data preprocessed with both 6B_300 glove and 840B_300 glove vectors that I converted to word2vec format using gensim.

**Comment by mahnerak** [comment]
Please follow instructions (you can find them in README.md).

It looks like you included raw string representations for character-level embedding in preprocessed data, but you have not enabled character-level embedding support in training script, which cause data format mismatch.
Consider providing `--char_level_embeddings ` flag to script `train.py` (as it's done in instructions) or remove `--include_str` when running script `preprocessing.py` (this one will disable character-level embedding support).

**Comment by mahnerak** [comment]
@konrajak Fixed
